apiVersion: fluxcd.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hashi-vault
  namespace: util
spec:
  interval: 10m
  chart:
    spec:
      chart: vault
      version: 0.19.0
      sourceRef:
        kind: HelmRepository
        name: hashi-vault
        namespace: util
  releaseName: hashi-vault
  values:
    ui:
      enabled: true
      serviceType: NodePort